const translations = {
    en: {
        home: 'Home',
        news: 'News',
        missions: 'Missions',
        guides: 'Guides',
        redeem: 'Redeem Codes',
        dashboard: 'Dashboard',
        contact: 'Contact',
        'home-title': 'Welcome to PUBG Pro Hub',
        'home-desc': 'Complete guide for Pakistani PUBG players! Get latest updates, missions, tips, and redeem codes in Urdu and English.',
        explore: 'Explore Now',
        'news-title': 'Latest PUBG Updates',
        'news-aespa': 'PUBG x aespa Collaboration',
        'news-aespa-desc': 'July 2025 update adds aespa-themed skins and new lobby music.',
        'news-transformers': 'Transformers Mode',
        'news-transformers-desc': 'New hotdrop mode in PUBG Mobile with Optimus Prime and Megatron.',
        'missions-title': 'Latest PUBG Missions',
        'all-platforms': 'All Platforms',
        'search-missions': 'Search missions...',
        'survivor-pass': 'Survivor Pass: Kiss the Sun',
        'survivor-pass-desc': 'Complete daily, weekly, and season missions to earn summer-themed skins. Example: Deal 500 damage (Daily), Win 1 match (Weekly).',
        'aespa-mission': 'PUBG x aespa Collaboration',
        'aespa-mission-desc': 'Play 5 matches on Erangel or get 2 kills with C4 to craft aespa-themed skins.',
        'transformers-mission': 'Transformers Collaboration',
        'transformers-mission-desc': 'Deal 1,000 damage as Optimus Prime or Megatron in hotdrops. Rewards: Energon Cubes.',
        'summer-showdown': 'Summer Showdown',
        'summer-showdown-desc': 'Use Ink Blaster to hit 10 enemies or defeat Giant Ice Dragon in World of Wonder.',
        'guides-title': 'Gameplay Guides & Tips',
        'weapon-guide': 'Best Weapons',
        'weapon-guide-desc': 'Master the M416 for versatility or AWM for sniping. Check weapon stats and recoil tips.',
        'login-fix': 'Fix Login Issues',
        'login-fix-desc': 'Check internet, verify credentials, or use GearUP Booster to reduce latency.',
        'redeem-title': 'Redeem Codes',
        'redeem-desc': 'No active codes for February 2025, but try expired codes for Venetian Crate.',
        'redeem-code': 'Enter redeem code',
        'redeem-btn': 'Redeem',
        'dashboard-title': 'User Dashboard',
        'dashboard-desc': 'Track your mission progress, view stats, and manage orders. Login required.',
        login: 'Login',
        'contact-title': 'Contact Us',
        'contact-desc': 'Reach out via WhatsApp, email, or support ticket for PUBG help. Join our Pakistani community WhatsApp group!',
        whatsapp: 'WhatsApp: +923481143077',
        email: 'Email: support@pubgprohub.com',
        community: 'Join WhatsApp Group',
        ticket: 'Submit Ticket',
        footer: '© 2025 PUBG Pro Hub. All rights reserved. Powered by xAI.'
    },
    ur: {
        home: 'ہوم',
        news: 'تازہ خبریں',
        missions: 'مشنز',
        guides: 'گائیڈز',
        redeem: 'ریڈیم کوڈز',
        dashboard: 'ڈیش بورڈ',
        contact: 'رابطہ',
        'home-title': 'پب جی پرو ہب میں خوش آمدید',
        'home-desc': 'پاکستانی پب جی پلیئرز کے لئے مکمل گائیڈ! اردو اور انگریزی میں تازہ اپ ڈیٹس، مشنز، ٹپس، اور ریڈیم کوڈز حاصل کریں۔',
        explore: 'ابھی دریافت کریں',
        'news-title': 'تازہ پب جی اپ ڈیٹس',
        'news-aespa': 'پب جی x ایپا تعاون',
        'news-aespa-desc': 'جولائی 2025 کی اپ ڈیٹ میں ایپا تھیم والی سکنز اور نئی لابی میوزک شامل۔',
        'news-transformers': 'ٹرانسفارمرز موڈ',
        'news-transformers-desc': 'پب جی موبائل میں آپٹیمس پرائم اور میگاٹرون کے ساتھ نیا ہاٹ ڈراپ موڈ۔',
        'missions-title': 'تازہ ترین پب جی مشنز',
        'all-platforms': 'تمام پلیٹ فارمز',
        'search-missions': 'مشنز تلاش کریں...',
        'survivor-pass': 'سروائیور پاس: کس دی سن',
        'survivor-pass-desc': 'روزانہ، ہفتہ وار، اور سیزن مشنز مکمل کریں تاکہ سمر تھیم والی سکنز حاصل ہوں۔ مثال: 500 ڈیمیج (روزانہ)، 1 میچ جیت (ہفتہ وار)۔',
        'aespa-mission': 'پب جی x ایپا تعاون',
        'aespa-mission-desc': 'ایرانجل پر 5 میچز کھیلیں یا C4 سے 2 کِلز حاصل کریں تاکہ ایپا سکنز بنائیں۔',
        'transformers-mission': 'ٹرانسفارمرز تعاون',
        'transformers-mission-desc': 'ہاٹ ڈراپس میں آپٹیمس پرائم یا میگاٹرون کے طور پر 1,000 ڈیمیج دیں۔ انعام: انرجن کیوبز۔',
        'summer-showdown': 'سمر شو ڈاؤن',
        'summer-showdown-desc': 'ورلڈ آف ونڈر میں انک بلاسٹر سے 10 دشمنوں کو ہٹ کریں یا جائنٹ آئس ڈریگن کو ہرائیں۔',
        'guides-title': 'گیم پلے گائیڈز اور ٹپس',
        'weapon-guide': 'بہترین ہتھیار',
        'weapon-guide-desc': 'M416 کو ورسٹائلٹی کے لئے یا AWM کو سناپنگ کے لئے استعمال کریں۔ ہتھیاروں کے اسٹیٹس اور ریکائل ٹپس چیک کریں۔',
        'login-fix': 'لاگ ان مسائل حل کریں',
        'login-fix-desc': 'انٹرنیٹ چیک کریں، کریڈینشلز کی تصدیق کریں، یا GearUP بوسٹر سے لیٹنسی کم کریں۔',
        'redeem-title': 'ریڈیم کوڈز',
        'redeem-desc': 'فروری 2025 کے لئے کوئی ایکٹو کوڈز نہیں، لیکن وینیشین کریٹ کے لئے ایکسپائرڈ کوڈز آزمائیں۔',
        'redeem-code': 'ریڈیم کوڈ درج کریں',
        'redeem-btn': 'ریڈیم کریں',
        'dashboard-title': 'صارف ڈیش بورڈ',
        'dashboard-desc': 'اپنے مشن کی پیشرفت ٹریک کریں، اسٹیٹس دیکھیں، اور آرڈرز کا نظم کریں۔ لاگ ان ضروری ہے۔',
        login: 'لاگ ان',
        'contact-title': 'ہم سے رابطہ کریں',
        'contact-desc': 'واٹس ایپ، ای میل، یا سپورٹ ٹکٹ کے ذریعے پب جی کی مدد حاصل کریں۔ پاکستانی کمیونٹی کے لئے واٹس ایپ گروپ جوائن کریں!',
        whatsapp: 'واٹس ایپ: +923481143077',
        email: 'ای میل: support@pubgprohub.com',
        community: 'واٹس ایپ گروپ جوائن کریں',
        ticket: 'ٹکٹ جمع کروائیں',
        footer: '© 2025 پب جی پرو ہب۔ جملہ حقوق محفوظ ہیں۔ xAI کے ذریعے تقویت یافتہ۔'
    }
};